from pathlib import Path
import requests,json,re,html,concurrent.futures,math
from PIL import Image,ImageDraw,ImageFont
ROOT=Path('/home/user/hollywood_full');CACHE=Path('/home/user/.cache/hollywood_full/photo_candidates');CACHE.mkdir(parents=True,exist_ok=True)
HEAD={'User-Agent':'ArenaPhotoPreview/2.0 (https://arena.ai; attributed archival photo documentary)'}
API='https://commons.wikimedia.org/w/api.php'
CAST=[
('Tom Cruise',1989,2025),('Leonardo DiCaprio',2000,2025),('Tom Hanks',1989,2024),
('Brad Pitt',2001,2024),('Keanu Reeves',2006,2025),('Johnny Depp',1992,2023),
('Denzel Washington',1990,2025),('George Clooney',1995,2025),('Matt Damon',2001,2024),
('Ben Affleck',1998,2023),('Will Smith',1993,2025),('Robert Downey Jr.',1990,2026),
('Harrison Ford',2007,2025),('Morgan Freeman',1990,2023),('Robert De Niro',1988,2025),
('Al Pacino',1996,2022),('Michael Douglas',1984,2025),('Jeff Bridges',2000,2025),
('Kevin Bacon',2004,2025),('Samuel L. Jackson',2008,2024),
('Arnold Schwarzenegger',1984,2025),('Sylvester Stallone',1985,2025),('Nicolas Cage',2007,2022),
('Hugh Jackman',2003,2025),('Christian Bale',1988,2022),('Ryan Reynolds',2007,2025),
('Ryan Gosling',2007,2023),('Jake Gyllenhaal',2005,2025),('Matthew McConaughey',2004,2025),('Ewan McGregor',2001,2024)]

def clean(value):return html.unescape(re.sub('<[^>]+>','',value or '')).strip()
def simple(page,year):
    if 'imageinfo' not in page:return None
    ii=page['imageinfo'][0];md=ii.get('extmetadata',{})
    v=lambda k:clean(md.get(k,{}).get('value',''))
    return {'pageid':page['pageid'],'title':page['title'],'url':ii['url'].split('?')[0],
            'source':ii['descriptionurl'],'width':ii['width'],'height':ii['height'],
            'year':year,'date':v('DateTimeOriginal'),'description':v('ImageDescription'),
            'artist':v('Artist'),'license':v('LicenseShortName'),'license_url':v('LicenseUrl'),
            'credit':v('Credit')}

def get_category(name,year):
    catname='Robert Downey, Jr.' if name=='Robert Downey Jr.' else name
    file=ROOT/'research'/('pool_'+name.replace(' ','_')+'_'+str(year)+'.json')
    if file.exists():return json.loads(file.read_text())
    p={'action':'query','format':'json','generator':'categorymembers','gcmtitle':f'Category:{catname} in {year}',
       'gcmtype':'file','gcmlimit':'50','prop':'imageinfo','iiprop':'url|size|extmetadata'}
    r=requests.get(API,params=p,headers=HEAD,timeout=45);r.raise_for_status();d=r.json()
    pages=d.get('query',{}).get('pages',{})
    out=[simple(x,year) for x in pages.values()];out=[x for x in out if x]
    file.write_text(json.dumps(out,ensure_ascii=False,indent=2));return out

def score(p,name):
    title=p['title'].lower();desc=p['description'].lower();both=title+' '+desc
    if not re.search(r'\.(jpe?g|png)$',title):return -999
    if not any(s in p['license'] for s in ['CC BY','Public domain','CC0']):return -999
    if any(s in both for s in ['wax figure','waxwork','sculpture','caricature','drawing','signature','autograph','statuette','generated by ai','ai-generated','painting','oil on canvas']):return -999
    # Do not use material dated after the current date.
    dat=re.search(r'\b(2026)-(\d{2})-(\d{2})',p['date'])
    if dat and dat.group(0)>'2026-09-05':return -999
    if min(p['width'],p['height'])<180:return -999
    s=0.;aspect=p['width']/p['height']
    s+=7 if .58<aspect<.95 else (4 if .95<=aspect<1.1 else -1)
    s+=min(5,math.log2(max(min(p['width'],p['height']),1)/200)*2)
    n=name.lower().replace(' jr.','').replace('.','').replace(',','')
    t=title.replace('.','').replace(',','')
    if t.startswith('file:'+n):s+=5
    if 'cropped' in title or '(crop)' in title:s+=5
    if 'portrait' in title or 'headshot' in title:s+=3
    if ' and ' in title or ' & ' in title or ' with ' in title:s-=7
    if 'group' in both:s-=4
    if any(a in p['artist'] for a in ['Harald Krichel','Georges Biard','Gage Skidmore','Alan Light','Raph_PH']):s+=2
    if str(p['year']) in p['date']:s+=1
    if aspect>1.65:s-=3
    return s

# Reuse the six approved, dated images from the short demo.
old=json.loads(Path('/home/user/hollywood_demo/work/photo_manifest.json').read_text())
REUSE={
(0,'then'):('cruise_then_wide',Path('/home/user/hollywood_demo/assets/cruise_then_wide.jpg')),
(0,'now'):('cruise_now_b',Path('/home/user/hollywood_demo/assets/cruise_now_b.jpg')),
(1,'then'):('leo_then',Path('/home/user/hollywood_demo/assets/leo_then.jpg')),
(1,'now'):('leo_now_b',Path('/home/user/hollywood_demo/assets/leo_now_b.jpg')),
(2,'then'):('hanks_then',Path('/home/user/hollywood_demo/assets/hanks_then.jpg')),
(2,'now'):('hanks_now_b',Path('/home/user/hollywood_demo/assets/hanks_now_b_large.jpg')),
}

def process(item):
    i,era,year=item;name=CAST[i][0]
    if (i,era) in REUSE:
        key,path=REUSE[i,era];p=old[key]
        q={'title':p['title'],'source':p['source'],'url':p['download'].split('?')[0],
           'width':p['width'],'height':p['height'],'year':year,'date':p['date_metadata'],
           'description':p['description'],'artist':p['artist'],'license':p['license'],
           'license_url':p['license_url'],'credit':p.get('credit',''),'reuse_path':str(path)}
        return f'{i:02d}_{era}',[q]
    if name=='Michael Douglas':
        d=json.loads((ROOT/'research/search_Michael_Douglas.json').read_text())
        pages=[simple(p,year) for p in d['query']['pages'].values()]
        pool=[p for p in pages if p and str(year) in (p['date']+' '+p['title'])]
    else:pool=get_category(name,year)
    for p in pool:p['score']=score(p,name)
    pool=sorted([p for p in pool if p['score']>-900],key=lambda p:p['score'],reverse=True)
    # Avoid showing an original and its crop as both candidates when alternatives exist.
    picks=[]
    for p in pool:
        if len(picks)==2:break
        base=re.sub(r'\s*\((crop|cropped|square)\)\s*','',p['title'],flags=re.I)
        if any(base==re.sub(r'\s*\((crop|cropped|square)\)\s*','',q['title'],flags=re.I) for q in picks):continue
        picks.append(p)
    return f'{i:02d}_{era}',picks

if __name__=='__main__':
    tasks=[(i,era,y) for i,(_,a,b) in enumerate(CAST) for era,y in [('then',a),('now',b)]]
    candidates={}
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as ex:
        for key,picks in ex.map(process,tasks):
            candidates[key]=picks
            print(key,CAST[int(key[:2])][0], ' | '.join(p['title'] for p in picks) if picks else 'EMPTY',flush=True)
    (ROOT/'research/candidates.json').write_text(json.dumps(candidates,ensure_ascii=False,indent=2))
    (ROOT/'research/cast.json').write_text(json.dumps([dict(name=n,years=[a,b]) for n,a,b in CAST],indent=2))
