from pathlib import Path
import requests,json,re,html,math,concurrent.futures,hashlib,time
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parent
CACHE=Path('/home/user/.cache/hollywood_actresses');(CACHE/'previews').mkdir(parents=True,exist_ok=True)
API='https://commons.wikimedia.org/w/api.php'
HEAD={'User-Agent':'ArenaPhotoPreview/2.0 (https://arena.ai; attributed archival photo documentary)'}
CAST=[
('Julia Roberts',1990,2025),('Angelina Jolie',2003,2025),('Nicole Kidman',2001,2025),
('Kate Winslet',2006,2025),('Sandra Bullock',1996,2025),('Cameron Diaz',2002,2026),
('Winona Ryder',2008,2024),('Demi Moore',1989,2026),('Meg Ryan',2006,2025),
('Halle Berry',1996,2025),('Charlize Theron',2005,2026),('Sharon Stone',1989,2026),
('Salma Hayek',1998,2025),('Cate Blanchett',2005,2025),('Anne Hathaway',2006,2026),
('Natalie Portman',2006,2025),('Scarlett Johansson',2003,2025),('Penélope Cruz',1992,2024),
('Lucy Liu',1986,2025),('Uma Thurman',1994,2024),('Jodie Foster',1989,2026),
('Sigourney Weaver',1989,2025),('Jamie Lee Curtis',1989,2025),('Meryl Streep',1989,2026)]
CATS=json.loads((ROOT/'research/year_categories.json').read_text())
def clean(s):return re.sub(r'\s+',' ',re.sub('<[^>]+>','',html.unescape(html.unescape(s or '')))).strip()
def simpl(p,y):
 if 'imageinfo' not in p:return None
 ii=p['imageinfo'][0];m=ii.get('extmetadata',{});v=lambda k:clean(m.get(k,{}).get('value',''))
 return dict(title=p['title'],pageid=p['pageid'],source=ii['descriptionurl'],url=ii['url'].split('?')[0],width=ii['width'],height=ii['height'],year=y,date=v('DateTimeOriginal'),description=v('ImageDescription'),artist=v('Artist'),license=v('LicenseShortName'),license_url=v('LicenseUrl'),credit=v('Credit'))
def query_category(cat,y,depth=0):
 p={'action':'query','format':'json','generator':'categorymembers','gcmtitle':cat,'gcmtype':'file','gcmlimit':'50','prop':'imageinfo','iiprop':'url|size|extmetadata'}
 d=requests.get(API,params=p,headers=HEAD,timeout=40).json();result=[simpl(p,y) for p in d.get('query',{}).get('pages',{}).values()];result=[p for p in result if p]
 if len(result)<3 and depth<1:
  p={'action':'query','format':'json','list':'categorymembers','cmtitle':cat,'cmtype':'subcat','cmlimit':'20'}
  dd=requests.get(API,params=p,headers=HEAD,timeout=35).json()
  for child in dd.get('query',{}).get('categorymembers',[])[:3]:
   if str(y) in child['title']:result+=query_category(child['title'],y,depth+1)
 return result

def pool(name,y):
 path=ROOT/'research'/('pool_'+name.replace(' ','_')+'_'+str(y)+'.json')
 if path.exists():return json.loads(path.read_text())
 if name in ['Lucy Liu','Meg Ryan']:
  d=json.loads((ROOT/'research'/('root_'+name.replace(' ','_')+'.json')).read_text());a=[simpl(p,y) for p in d['query']['pages'].values()];a=[p for p in a if p and str(y) in p['title']+' '+p['date']]
 else:
  key='Anne Hathaway (actress)' if name=='Anne Hathaway' else name
  cats=CATS.get(key,{}).get('categories',[])
  cat=next((p['title'] for p in cats if p['title'].endswith(' in '+str(y))),f'Category:{name} in {y}')
  a=query_category(cat,y)
 path.write_text(json.dumps(a,ensure_ascii=False,indent=2));return a

def score(p,name):
 t=p['title'].lower();d=p['description'].lower();both=t+' '+d
 if not re.search(r'\.(jpg|jpeg|png)$',t):return -999
 if not any(x in p['license'] for x in ['CC BY','Public domain','CC0']):return -999
 if min(p['width'],p['height'])<160:return -999
 if any(w in both for w in ['waxwork','wax figure','signature','caricature','statue','sculpture','painting','generated by ai','ai-generated','restoration by ai','movie poster','film poster']):return -999
 match=re.search(r'\b2026-\d\d-\d\d',p['date'])
 if match and match.group()>'2026-09-05':return -999
 # A date mismatch between the chosen year and source date is flagged for review,
 # and not silently treated as the upload year or a synthetic 'now'.
 surname=name.split()[-1].lower();aspect=p['width']/p['height'];s=0.
 s+=8 if .62<aspect<.94 else 4 if .94<=aspect<1.12 else 0
 s+=min(4,math.log2(max(100,min(p['width'],p['height']))/250)*2)
 if name.lower() in t:s+=6
 elif surname in t:s+=3
 else:s-=4
 if '(cropped)' in t or '(crop)' in t or '(square)' in t:s+=5
 if ' and ' in t or ' & ' in t or ' with ' in t:s-=11
 if any(w in t for w in ['james','keith urban','tom cruise','morgan freeman','harrison ford','julianne moore']) and name.lower() not in t:s-=20
 if 'portrait' in t or 'headshot' in t:s+=2
 if str(p['year']) in p['date']:s+=2
 if any(n in p['artist'] for n in ['Alan Light','Harald Krichel','Georges Biard','Raph_PH','Gabriel Hutchinson','Gage Skidmore']):s+=1
 return s

def collect(task):
 i,e,y=task;name=CAST[i][0];a=pool(name,y)
 for p in a:p['score']=score(p,name)
 a=sorted([p for p in a if p['score']>-900],key=lambda p:p['score'],reverse=True)
 selected=[]
 for p in a:
  base=re.sub(r'\s*\((cropped[^)]*|crop|square)\)\s*','',p['title'],flags=re.I)
  if any(base==re.sub(r'\s*\((cropped[^)]*|crop|square)\)\s*','',q['title'],flags=re.I) for q in selected):continue
  selected.append(p)
  if len(selected)==2:break
 return f'{i:02d}_{e}',selected

def download(item):
 key,j,p=item;u=p['url'];path=CACHE/'previews'/(key+'_'+str(j)+'_'+hashlib.sha1(u.encode()).hexdigest()[:8]+'.jpg')
 if path.exists():return key,j,str(path)
 w=250
 if p['width']>w:u=u.replace('upload.wikimedia.org/wikipedia/commons/','thumb.wikimedia.org/wikipedia/commons/thumb/')+f'/{w}px-'+u.split('/')[-1]
 try:
  r=requests.get(u,headers=HEAD,timeout=35);r.raise_for_status();path.write_bytes(r.content);Image.open(path).verify();return key,j,str(path)
 except Exception as ex:return key,j,'ERROR: '+str(ex)

def boards(c):
 f=ImageFont.truetype('/home/user/hollywood_full/assets/fonts/Manrope.ttf',13);f2=ImageFont.truetype('/home/user/hollywood_full/assets/fonts/Manrope.ttf',18)
 for page in range(6):
  cv=Image.new('RGB',(1040,1180),'#15161d');d=ImageDraw.Draw(cv)
  for row,i in enumerate(range(page*4,min(24,page*4+4))):
   y=row*295;d.text((10,y+3),f'{i:02d}  {CAST[i][0]}  {CAST[i][1]} / {CAST[i][2]}',font=f2,fill='white')
   for e,off in [('then',0),('now',2)]:
    for j,p in enumerate(c[f'{i:02d}_{e}']):
     x=(off+j)*260;path=p.get('preview','')
     if path and not path.startswith('ERROR'):
      im=Image.open(path).convert('RGB');im.thumbnail((246,220));cv.paste(im,(x+(260-im.width)//2,y+32+(220-im.height)//2))
     d.text((x+5,y+258),e.upper()+f' {j} / '+p['title'].replace('File:','')[:20],font=f,fill='#c1adff')
  cv.save(CACHE/'previews'/f'board_{page+1}.jpg',quality=92)

if __name__=='__main__':
 c={};tasks=[(i,e,y) for i,(_,a,b) in enumerate(CAST) for e,y in [('then',a),('now',b)]]
 with concurrent.futures.ThreadPoolExecutor(max_workers=3) as ex:
  for key,a in ex.map(collect,tasks):c[key]=a;print(key,CAST[int(key[:2])][0], ' | '.join(p['title'] for p in a) if a else 'EMPTY',flush=True)
 (ROOT/'research/photo_candidates.json').write_text(json.dumps(c,ensure_ascii=False,indent=2))
 with concurrent.futures.ThreadPoolExecutor(max_workers=2) as ex:
  for key,j,path in ex.map(download,[(k,j,p) for k,a in c.items() for j,p in enumerate(a)]):
   c[key][j]['preview']=path
   if path.startswith('ERROR'):print(key,path,flush=True)
 (ROOT/'research/photo_candidates.json').write_text(json.dumps(c,ensure_ascii=False,indent=2));boards(c)
 (ROOT/'research/cast_provisional.json').write_text(json.dumps([{'name':n,'years':[a,b]} for n,a,b in CAST],ensure_ascii=False,indent=2))
 print('BOARDS_READY',flush=True)
